version: "3.0"

services:
  givebirthtome-site:
    image: jekyll/jekyll:3.8.5
    container_name: givebirthtome-site
    volumes:
      - .:/srv/jekyll
    ports:
      - 8080:4000
    entrypoint: jekyll serve --trace #-H localhost
